In [2]:
# organize dataset into a useful structure
from os import makedirs
from os import listdir
from shutil import copyfile
from random import seed
from random import random

In [5]:
import tensorflow as tf

from tensorflow.keras import datasets, layers, models
import matplotlib.pyplot as plt

In [6]:
!pip install opencv-python

In [7]:
import cv2

In [8]:
img=cv2.imread(r"C:\Users\Pooja\Documents\Cat Vs Dog\data\train\cats\cat.1.jpg")

In [9]:
print(img)

[[[ 40  44  39]
  [ 40  44  39]
  [ 43  44  40]
  ...
  [173 204 207]
  [166 199 202]
  [163 198 201]]

 [[ 41  45  40]
  [ 41  45  40]
  [ 43  44  40]
  ...
  [169 200 203]
  [163 196 199]
  [159 194 197]]

 [[ 41  45  40]
  [ 41  45  40]
  [ 43  44  40]
  ...
  [166 195 199]
  [164 194 199]
  [162 194 199]]

 ...

 [[ 31  30  32]
  [ 29  28  30]
  [ 25  24  26]
  ...
  [ 17  23  36]
  [ 24  30  41]
  [ 40  46  57]]

 [[ 31  30  32]
  [ 29  28  30]
  [ 25  24  26]
  ...
  [ 21  29  42]
  [ 25  34  44]
  [ 36  45  55]]

 [[ 31  30  32]
  [ 28  27  29]
  [ 24  23  25]
  ...
  [ 30  38  51]
  [ 23  32  42]
  [ 21  30  40]]]


In [10]:
#cv2.imshow("Result",img)
#cv2.waitKey(0)
#cv2.destroyAllWindows

In [11]:
#cv2.destroyAllWindows()

In [12]:
from keras.preprocessing.image import ImageDataGenerator

In [13]:
datagen = ImageDataGenerator(
    featurewise_center=True,
    featurewise_std_normalization=True,
    rotation_range=20,
    width_shift_range=0.2,
    height_shift_range=0.2,
    horizontal_flip=True,
    validation_split=0.2,
    rescale = 1/255.0)

In [14]:
train_datagen = ImageDataGenerator(
        rescale=1./255,
        shear_range=0.2,
        zoom_range=0.2,
        horizontal_flip=True)
test_datagen = ImageDataGenerator(rescale=1./255)
train_generator = train_datagen.flow_from_directory(
        'data/train',
        target_size=(150, 150),
        batch_size=32,
        class_mode='binary')
validation_generator = test_datagen.flow_from_directory(
        'data/validation',
        target_size=(150, 150),
        batch_size=32,
        class_mode='binary')


Found 18697 images belonging to 2 classes.
Found 6303 images belonging to 2 classes.


In [15]:
model = models.Sequential()
model.add(layers.Conv2D(32, (3, 3), activation='relu', input_shape=(150, 150, 3)))
model.add(layers.MaxPooling2D((2, 2)))
model.add(layers.Conv2D(64, (3, 3), activation='relu'))
model.add(layers.MaxPooling2D((2, 2)))
model.add(layers.Conv2D(64, (3, 3), activation='relu'))

In [16]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d (Conv2D)             (None, 148, 148, 32)      896       
                                                                 
 max_pooling2d (MaxPooling2D  (None, 74, 74, 32)       0         
 )                                                               
                                                                 
 conv2d_1 (Conv2D)           (None, 72, 72, 64)        18496     
                                                                 
 max_pooling2d_1 (MaxPooling  (None, 36, 36, 64)       0         
 2D)                                                             
                                                                 
 conv2d_2 (Conv2D)           (None, 34, 34, 64)        36928     
                                                                 
Total params: 56,320
Trainable params: 56,320
Non-traina

In [17]:
model.add(layers.Flatten())
model.add(layers.Dense(64, activation='sigmoid'))
model.add(layers.Dense(1))

In [18]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d (Conv2D)             (None, 148, 148, 32)      896       
                                                                 
 max_pooling2d (MaxPooling2D  (None, 74, 74, 32)       0         
 )                                                               
                                                                 
 conv2d_1 (Conv2D)           (None, 72, 72, 64)        18496     
                                                                 
 max_pooling2d_1 (MaxPooling  (None, 36, 36, 64)       0         
 2D)                                                             
                                                                 
 conv2d_2 (Conv2D)           (None, 34, 34, 64)        36928     
                                                                 
 flatten (Flatten)           (None, 73984)             0

In [ ]:
model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy'])

history = model.fit(train_generator ,validation_data = validation_generator,epochs=10,batch_size=32 )

Epoch 1/10
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: 'arguments' object has no attribute 'posonlyargs'
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: 'arguments' object has no attribute 'posonlyargs'
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
585/585 [==============================] - ETA: 0s - loss: 7.5942 - accuracy: 0.5013WARNING:tensorflow:AutoGraph could not transform <function Model.make_test_function.<locals>.test_function at 0x0000025D808AA510> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`